import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'PRINCIPAL',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/admin/dashboard/main',
    title: 'Inicio',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'assessment',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/usuarios/todos-usuarios',
    title: 'Usuarios',
    moduleName: 'usuarios',
    iconType: 'material-icons-two-tone',
    icon: 'assignment_ind',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/estudiantes/todos-estudiantes',
    title: 'Estudiantes',
    moduleName: 'estudiantes',
    iconType: 'material-icons-two-tone',
    icon: 'book',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },
  {
    path: '/admin/cursos/todos-cursos',
    title: 'Cursos',
    moduleName: 'cursos',
    iconType: 'material-icons-two-tone',
    icon: 'view_list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
  },


  

  // Common Module

  {
    path: '/estudiante/dashboard',
    title: 'MENUITEMS.STUDENT.LIST.DASHBOARD',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['estudiante'],
    submenu: [],
  },
  {
    path: '/estudiante/cursosDisponibles/todos-cursos',
    title: 'Cursos Disponibles',
    moduleName: 'cursosDisponibles',
    iconType: 'material-icons-two-tone',
    icon: 'view_list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['estudiante'],
    submenu: [],
  },
  {
    path: '/estudiante/cursosRegistrados/todos-cursos',
    title: 'Cursos Registrados',
    moduleName: 'cursosRegistrados',
    iconType: 'material-icons-two-tone',
    icon: 'grid_on',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['estudiante'],
    submenu: [],
  },
];
